### ISSUE TITLE
Smoketest samples using learning transport

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.AzureStorage#142] opened 2017-05-16 08:36 UTC
https://github.com/Particular/docs.particular.net/pull/2724#issuecomment-301449055

**Comment by SimonCropp** [comment] 2017-05-18 01:20
for the ones that cant use the learning persistence and transport can u also list the reasons why

**Comment by SimonCropp** [comment] 2017-05-18 01:21
for example i assume the databus sample be able to use both the learning persistence and transport

**Comment by SeanFeldman** [comment] 2017-05-18 02:05
@SimonCropp you mean marking off in the parent issue?
![image](https://cloud.githubusercontent.com/assets/1309622/26183486/373fd5b2-3b3c-11e7-8c09-083789cab2c5.png)

**Comment by SimonCropp** [comment] 2017-05-18 02:19
@SeanFeldman that is already closed. i will need to track on your own issue

**Comment by SeanFeldman** [comment] 2017-05-18 02:20
Shouldn't have been closed if there's no other issue to track... I'll do it on the PR then and ping the maintainers. PR should be only merged when all confirmed.

**Comment by SimonCropp** [comment] 2017-05-18 02:24
> Shouldn't have been closed if there's no other issue to track

the remaining items are covered by this issue.

**Comment by SimonCropp** [comment] 2017-05-18 02:25
> I'll do it on the PR then and ping the maintainers. 

just raise a new PR

**Comment by SeanFeldman** [comment] 2017-05-18 02:49
This will be handled by https://github.com/Particular/docs.particular.net/issues/2747

**Closed by SeanFeldman** 2017-05-18 02:49 UTC
