### ISSUE TITLE
New Saga Instances Cause Table Scan Leading to Unacceptable Performance

### ISSUE THREAD

**Issue by tekmaven** [Particular/NServiceBus.Persistence.AzureStorage#130] opened 2017-02-15 17:27 UTC
## Who's affected

* Anyone using NServiceBus.Persistence.AzureStorage

## Symptoms

* New sagas cause full table scans that can influence the performance significantly.

## Original issue 

I'm using the latest 5.x code, but this is still an issue in 6.x.

Any time a new saga instance is created (which means there has not been a secondary index entity created), 
the saga persister performs a table scan.  

This is due to this line: https://github.com/Particular/NServiceBus.Persistence.AzureStorage/blob/develop/src/NServiceBus.Persistence.AzureStorage/SagaPersisters/AzureSagaPersister.cs#L190

It is really because we need to be able to use `PartitionKey` and `RowKey` in the storage persistence.

**Comment by boblangley** [comment] 2017-02-16 21:30
@tekmaven Yes, we have confirmed what you say is true. This is by design.

<= 6.2.3 versions of the persistence contained flaw which did not provide a way to take advantage of primary keys when searching for saga instances, resulting in full table scans. We correct this flaw by introducing a secondary index record, using the correlation id as the `PrimaryKey` and the saga id as the `RowKey`. 

So the new behavior is this:

1. Saga is accessed using the primary index when the saga id is known from message headers.
2. If the saga id is not known, the correlation id is used to look up secondary index record.
3. If no secondary index record is found, then a full table scan is performed in an attempt to locate an existing pre-6.2.4 saga that has no secondary index record.
4. If pre-6.2.4 saga is located using the full table scan, the secondary index record is created.
5. If no saga is located (and the message starts the saga), we will create both the primary index saga record, and the secondary index record for the saga.

Over time all of the pre-6.2.4 sagas would be migrated as they are accessed eventually eliminating the need for full table scans.

The other option considered at the time was to have the endpoint create secondary index records for all of the pre-6.2.4 sagas at startup time. This was reject due to several concerns:

1. It could adversely affect startup times.
2. It would run at every startup.
3. Potential contention between concurrent scaled out endpoints performing the upgrade.

After reviewing this solution we have concluded we can do better by providing a one time, offline, upgrade script to create the missing secondary index records. I have opened #132 to track the creation of such a script.

**Comment by tekmaven** [comment] 2017-02-16 22:22
What about changes to Azure Storage to fully rely on the secondary index, and no longer do the table scan?  Will those changes be backported to the version that targets NSB v5?

**Comment by SeanFeldman** [comment] 2017-02-16 22:27
> What about changes to Azure Storage to fully rely on the secondary index, and no longer do the table scan? 

This is what we'll do in #132.

>Will those changes be backported to the version that targets NSB v5?

Correct.

**Comment by tekmaven** [comment] 2017-04-03 12:33
@SeanFeldman 

I'm not sure the severity of this issue is classified properly (it's currently a "feature" so lower priority?).  With this table scan in the new saga instance codepath, I'm not sure how anyone can use this transport reliably in a production environment.

**Comment by SeanFeldman** [comment] 2017-04-03 21:32
@tekmaven do you mean #132? That one is marked as a feature.

**Comment by tekmaven** [comment] 2017-04-04 01:03
Yes.  "Changes to Azure Storage to fully rely on the secondary index" sounds like a bug fix to me.  The bug was a design bug.

Again, I can not stress how unusable this persistence is in production without this change.  It's only good for video store demos right now.

**Comment by SeanFeldman** [comment] 2017-05-31 14:48
Escalating this internally to get resources and work on it.

**Comment by SeanFeldman** [comment] 2017-06-16 19:09
Closed via https://github.com/Particular/NServiceBus.Persistence.AzureStorage/commit/b803f2ce8e84d2866f16bfac4b4ae6623fc77394

**Closed by SeanFeldman** 2017-06-16 19:09 UTC
Labels: State: In Progress, Type: Bug
