### ISSUE TITLE
Illegal date in timeout persister (NServiceBus v5)

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.AzureStorage#178] opened 2017-10-13 17:28 UTC
[Link in Slack](https://particularsoftware.slack.com/archives/C1607JM6G/p1507915105000174)

Ramon Smits [7:18 PM] 
Having a strange issue with Azure persistence:

Ramon Smits [7:18 PM] 
added this Plain Text snippet

```
2017-11-14 21:29:35,822|WARN|17|NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver|Failed to fetch timeouts from the timeout storage
Microsoft.WindowsAzure.Storage.StorageException: OutOfRangeInput ---> System.Data.Services.Client.DataServiceRequestException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: {"odata.error":{"code":"OutOfRangeInput","message":{"lang":"en-US","value":"One of the request inputs is out of range.\nRequestId:d9d80396-0002-00cf-5187-5d1de6000000\nTime:2017-11-14T20:30:04.0364279Z"}}}
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.SaveResult.HandleResponse()
   at System.Data.Services.Client.BaseSaveResult.EndRequest()
   at System.Data.Services.Client.DataServiceContext.SaveChanges(SaveChangesOptions options)
   at Microsoft.WindowsAzure.Storage.Core.Executor.TableExecutor.ExecuteSync[T,INTERMEDIATE_TYPE](TableCommand`2 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.TableExecutor.ExecuteSync[T,INTERMEDIATE_TYPE](TableCommand`2 cmd, IRetryPolicy policy, OperationContext operationContext)
   at NServiceBus.Azure.TimeoutPersister.UpdateSuccessfulRead(ServiceContext context, TimeoutManagerDataEntity read) in C:\BuildAgent\work\32a824616368e685\src\NServiceBus.Azure\Timeout\TimeoutLogic\TimeoutPersister.cs:line 421
   at NServiceBus.Azure.TimeoutPersister.GetNextChunk(DateTime startSlice, DateTime& nextTimeToRunQuery) in C:\BuildAgent\work\32a824616368e685\src\NServiceBus.Azure\Timeout\TimeoutLogic\TimeoutPersister.cs:line 90
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.SpinOnce(DateTime startSlice) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPersisterReceiver.cs:line 100
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object obj) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPersisterReceiver.cs:line 82
   at System.Threading.Tasks.Task.Execute()
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:OutOfRangeInput
```

Add Comment Click to expand inline 38 lines

Ramon Smits [7:18 PM] 
> NServiceBus.ExpiredTimeoutsPoller|Failed to fetch timeouts from the timeout storage

[7:18] 
ErrorCode:OutOfRangeInput
ErrorMessage:The 'LastSuccessfullRead' parameter of value '01/01/0001 01:00:00' is out of range.

2017-10-13 16:44:11.4019|INFO| 1|AssemblyScanner|Loaded: NServiceBus.Persistence.AzureStorage (1.4.0+0.Branch.master.Sha.b803f2ce8e84d2866f16bfac4b4ae6623fc77394)
2017-10-13 16:44:11.4019|INFO| 1|AssemblyScanner|Loaded: NServiceBus6.x64 (0.0.0.0)

[7:21] 
Not sure what is wrong there.. but it seems we are specifying a DateTime.MinValue which isn't allowed

[7:21] 
Does this ring a bell?

**Comment by SeanFeldman** [comment] 2017-10-18 14:19
> '01/01/0001 01:00:00' 

That's off. Not an epoch date/time. Also, the minimum date/time should be `Now()` value.

**Comment by yvesgoeleven** [comment] 2017-10-20 12:06
Are these the same? https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/103

**Comment by SeanFeldman** [comment] 2017-10-20 18:23
They do look related, but why dates less than `DateTime.NowUtc` are passed in?

**Comment by SeanFeldman** [comment] 2017-10-25 05:56
Apparently the issue is not with the saga start date, but with the user data stored in a saga.

**Comment by SeanFeldman** [comment] 2017-10-25 14:17
> Are these the same? #103

No, it's not the same.

**Comment by ramonsmits** [comment] 2017-11-14 21:02
During a zoom call, I demonstrated the error to @SeanFeldman. We looked at the table data and didn't see anything obviously wrong. I purged the related tables and ran the test again and then it just worked as expected.

Closing this for now as I, unfortunately, cannot reproduce it anymore due to purging the table data.

**Closed by ramonsmits** 2017-11-14 21:02 UTC
Labels: State: Blocked
